name: 'Testing'

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: ['closed', 'synchronize', 'edited', 'opened', 'reopened']
    branches:
      - 'main'

env:
  FORCE_COLOR: 1

jobs:
  foo:
    name: 'Foo'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - name: 'Set environment variable sandbox'
        if: github.base_ref == 'main' && github.event.pull_request.state != 'closed'
        run: |
          echo "ENV = sandbox"
          echo "ENV=sandbox" >> ${GITHUB_ENV}
      - name: 'Set environment variable production'
        if: github.event.pull_request.state == 'closed' && github.event.pull_request.merged == true
        run: |
          echo "ENV = production"
          echo "ENV=production" >> ${GITHUB_ENV}
      - name: 'Show env variables and github stages stuff'
        run: |
          echo "Environment: ${{ env.ENV  }}"
          echo "Github Action: ${{ github.action }}"
          echo "Github Event: ${{ github.event_name }}"
          echo "Pull request payload: "
          echo "Base ref: ${{ github.event.pull_request.base.ref }}"
          echo "State: ${{ github.event.pull_request.state }}"
          echo "Merged at: ${{ github.event.pull_request.merged_at }}"
          echo "Pull request merged: ${{ github.event.pull_request.merged }}"
